### ISSUE TITLE
pywebview build failure

### ISSUE THREAD

**Issue by pabloinfo1** [5k-omar/Zefoy-Bot#1]
pywebview fails to install due to pythonnet compilation errors on Python 3.14. This causes a crash when the script tries to display the captcha: NameError: name 'webview' is not defined in ImgToWinFromBytes (line 125).

Implement a manual fallback to save the captcha as a PNG:
`def ImgToWinFromBytes(image_bytes):
    with open("captcha.png", "wb") as f:
        f.write(image_bytes)
    return input(" -> Enter Captcha: ")`

**Comment by 5k-omar** [comment]
pywebview fails to install on Python 3.14 because pythonnet does not build yet
This causes `NameError: name 'webview' is not defined` when the captcha window is opened.

I fixed this by adding a fallback for Python 3.14: when pywebview is unavailable, the captcha image is saved as a **png** and opened manually (no GUI window), and the user enters the captcha in the terminal

This avoids crashes and keeps the script working on Python 3.14

```python
try:
    import webview
    WEBVIEW_AVAILABLE = True
except Exception:
    webview = None
    WEBVIEW_AVAILABLE = False


def ImgToWinFromBytes(image_bytes):
    if not WEBVIEW_AVAILABLE:
        captcha_path = "captcha.png"
        with open(captcha_path, "wb") as f:
            f.write(image_bytes)
        
        sys_name = platform.system()
        try:
            if sys_name == "Windows":
                os.startfile(captcha_path)
            elif sys_name == "Darwin":
                os.system(f"open {captcha_path}")
            else:
                os.system(f"xdg-open {captcha_path}")
        except:
            pass
        
        return input(" -> Enter Captcha: ").strip()
```
